### ISSUE TITLE
Could you please add support for Traditional Chinese?

### ISSUE THREAD

**Issue by RayChen1996** [seven1m/bible_api#106]
Hello,

Thank you for your amazing work on the Bible API! I would like to kindly ask if it's possible to add support for Traditional Chinese (繁體中文) in the API. This would be really helpful for users in regions like Taiwan, Hong Kong, and Macau.

Thank you again for your consideration and efforts!

Best regards

**Comment by seven1m** [comment]
If you know of a public-domain bible file for the language, then please point me in the right direction!

**Comment by wupangyen** [comment]
Hi Ray! I was thinking about the same thing, it will be great if we can have 
Mandarin Chinese in the API.

Hi Tim! thank you for making this amazing Bible API for the developers around the world!

I did some research I know for Chinese Union Version is free to use for everyone because The copyright of the Chinese Union Version published in 1919 has long since expired. Now, anyone has the right to legally publish the Bible under the name “Union Version” without authorization from the United Bible Societies. [https://en.wikipedia.org/wiki/Chinese_Union_Version](url)

And I saw we have a repo for add new bible translations! 
[https://github.com/seven1m/open-bibles](url)

I got the Mandarin Chinese Bible Version(CUV) from this source [https://www.ph4.org/b4_1.php?l=zhT](url)
<img width="1323" alt="Screenshot 2024-12-20 at 5 14 51 PM" src="https://github.com/user-attachments/assets/9e70767a-51bd-4f5a-b3a0-032fe3c922ba" />

and convert it to the .xml format. Because I see the translations we have are all in that format in open-bibles repo

I am new to backend api stuff, but I will spend some time these days to figure out to create a pull request to add CUV this bible translation in open-bibles repo

Once again! Appreciate you Tim for making this Free Bible API available! 
And Ray hopefully we will have the Mandarin Chinese in the API soon!

Jesus loves you guys!

**Comment by wupangyen** [comment]
Just created a PR[#27 ](https://github.com/seven1m/open-bibles/pull/27)  in open bibles repo! thanks Tim!

**Comment by seven1m** [comment]
@wupangyen thanks so much. I'll take a look at it this weekend. If you don't mind, could you also make a PR to add Chinese to [this repo](https://github.com/seven1m/bible_ref), kind of like this file: https://github.com/seven1m/bible_ref/blob/master/lib/bible_ref/languages/portuguese.rb

**Comment by wupangyen** [comment]
@seven1m yea no problem! I can take a look these days and create a PR to add Chinese in bible_ref repo

**Comment by wupangyen** [comment]
> @seven1m yea no problem! I can take a look these days and create a PR to add Chinese in bible_ref repo

[Here is the PR](https://github.com/seven1m/bible_ref/pull/13) Thanks for taking the time looking at it!

**Comment by seven1m** [comment]
The database for bible-api.com has been updated with this new translation. 🎉

[https://bible-api.com/約翰福音+3:16?translation=cuv](https://bible-api.com/%E7%B4%84%E7%BF%B0%E7%A6%8F%E9%9F%B3+3:16?translation=cuv)

Thanks for all your hard work on this!

**Comment by wupangyen** [comment]
> The database for bible-api.com has been updated with this new translation. 🎉
> 
> [https://bible-api.com/約翰福音+3:16?translation=cuv](https://bible-api.com/%E7%B4%84%E7%BF%B0%E7%A6%8F%E9%9F%B3+3:16?translation=cuv)
> 
> Thanks for all your hard work on this!

God is so good!!!

**Comment by RayChen1996** [comment]
I would like to request a feature that lists all the verse locations related to my keyword search, allowing me to navigate directly to the specific chapter.


我想要請求一個功能，能在關鍵字搜尋後列出所有相關的經文位置，並讓我可以直接跳轉到對應的章節。
