### ISSUE TITLE
Missing book and verses

### ISSUE THREAD

**Issue by artenod1** [seven1m/bible_api#51]
Hello,

Thank you for providing this resource and all the work you do. I am learning how to build apps that make requests and have been working on building a simple bible app using this api. 
I am unable to get the book of Jude, 3 John 2-15, and 2 John 2-13. I could be doing something wrong but just wanted to let you know.

**Comment by csf30816** [comment]
Although I am not sure about receiving a whole book of the Bible, I can get verses from Jude and I can get all the verses you mentioned here.

Remember to use `:` as a separator instead of `-`.

`/jude 1:1` OR `/jud 1:1`
`/john 2:15` OR `/jhn 2:15`
`/john 2:13` OR `/jhn 2:13`

However, if you are trying to get John **chapters** 2 - 13, than do this:

`/john 2:1-13:38`

Make sure that your spacing and formatting is correct.

**Comment by seven1m** [comment]
Single-chapter books are handled slightly differently. Since a lot of people were trying to query something like "Jude 3" and getting nothing, we changed it so single-chapter books don't require the chapter number. Unfortunately, there's now no easy way to get the full chapter (book), since you cannot just ask for "Jude 1", since you now only get the first verse of the book.

The following do work:

- http://bible-api.com/jude+1 - first verse of Jude
- http://bible-api.com/jude+1:1 - also first verse of Jude
- http://bible-api.com/jude+3 - third verse of Jude
- http://bible-api.com/jude+1:3 - also third verse of Jude

To get the whole chapter, you'll have to specify the verse numbers:

- http://bible-api.com/jude+1-25

(The same applies to other single-chapter books such as 2 John and 3 John.)

See https://github.com/seven1m/bible_api/issues/25 for previous discussion.

**Comment by artenod1** [comment]
Ok, it is working now. Thank you for your help!

**Comment by seven1m** [comment]
FYI I added a note to the site about single-chapter books and an option to change the matching behavior. Please see the section "Single-Chapter Books" on the site here: https://bible-api.com
