### ISSUE TITLE
Bible book chapter range problem

### ISSUE THREAD

**Issue by akinsayo** [seven1m/bible_api#52]
Hello, 

Thank you for your API, its is simple, fast and very effective. 

In the course of use, I noticed a small issue. When a request is made as such:
https://bible-api.com/Isaiah:13-17

This ought to return everything in Isaiah chapter 13, 14... down to 17. However, it returns just chapters 13 and 17 alone.

Thank you

**Comment by seven1m** [comment]
We don't support chapter ranges by design, as the query and payload can be too large to handle without degrading the service for others.

If you want to display many chapters at once (or an entire book), there are more efficient ways to do it, e.g. store the text in your app.

This service is for verses or short passages. Thanks.
