### ISSUE TITLE
Getting a whole chapter

### ISSUE THREAD

**Issue by c-edh** [seven1m/bible_api#75]
Hi, first of all I want to thank you for making this API available to the public for free! 

I notice that there are a few chapters that wont fetch all the verses. For example trying to get all the verses for [3 John 1](https://bible-api.com/3jn%201) it will only get one verse from the chapter. While [1 John 1](https://bible-api.com/1jn%201) gets all the verses

**Comment by seven1m** [comment]
I am sorry about that, but I don't really have a good solution. Since 3 John is a single-chapter book, the chapter number is optional.

So just as 3 John 3 will return the third verse, 3 John 1 will return the first verse.

A bit more info here: https://github.com/seven1m/bible_api/issues/51#issuecomment-799456431

**Comment by seven1m** [comment]
I suspect you found this issue because you are scraping the entire API to fetch all books and chapters, yes?

Might I suggest using the source data here instead: [open-bibles](https://github.com/seven1m/open-bibles)
